### ISSUE TITLE
Please add the dependence on the gulp-util to dependencies

### ISSUE THREAD

**Issue by septs** [morlay/react-docgen-ui#1]
Shell Logger:

```
develop@develop ~/Projects/project $ npm install --save-dev react-docgen-ui
npm WARN optional dep failed, continuing fsevents@0.3.8
react-docgen-ui@0.1.2 node_modules/react-docgen-ui
├── classnames@2.1.3
├── marked@0.3.5
├── doctrine@0.6.4 (isarray@0.0.1, esutils@1.1.6)
├── react-router@0.13.3 (object-assign@2.1.1, qs@2.4.1)
├── codemirror@5.5.0
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── react-docgen@2.0.0 (node-dir@0.1.8, async@0.9.2, babylon@5.8.21, nomnom@1.8.1, recast@0.10.26)
├── babel-runtime@5.8.20 (core-js@1.0.1)
└── babel@5.8.21 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, commander@2.8.1, source-map@0.4.4, output-file-sync@1.1.1, glob@5.0.14, chokidar@1.0.5, babel-core@5.8.21)
develop@develop ~/Projects/project $ gulp build:docs
[14:26:07] Using gulpfile ~/Projects/project/gulpfile.js
[14:26:07] Starting 'build:docs'...
[14:26:07] 'build:docs' errored after 38 ms
[14:26:07] Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/develop/Projects/project/node_modules/react-docgen-ui/dist/index.js:19:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Process finished with exit code 1
```

Gulp Task Code:

```
gulp.task('build:docs', function () {
    return gulp.src('./src/components/**/*.js')
        .pipe(logger)
        .pipe(require('react-docgen-ui')())
        .pipe(gulp.dest('./dist/docs'));
});
```

**Comment by morlay** [comment]
Thanks :-)  fixed.
